### ISSUE TITLE
[Epic] Project DRSP (Upbound Docs)

### ISSUE THREAD

**Issue by julzvilla** [upbound/docs#165]
### Context
Project DRSP is an effort to restructure and re-style the Upbound Docs pages.

----

### Resources
- [Sketch designs](https://www.sketch.com/s/9c476952-055e-4919-b474-520fe563bff8)

----

```[tasklist]
### Tasks
- [ ] https://github.com/upbound/docs/issues/166
- [ ] https://github.com/upbound/docs/issues/167
- [ ] https://github.com/upbound/docs/issues/168
- [x] [Project DRSP] Create POC of collapsible subheaders in the side nav
```
