### ISSUE TITLE
[Project DRSP] Docs follow-on improvements

### ISSUE THREAD

**Issue by julzvilla** [upbound/docs#197]
### Context
Follow-on work based on feedback from the 7/28 release of https://github.com/upbound/docs/issues/165

----

### Resources
- [Sketch designs](https://www.sketch.com/s/9c476952-055e-4919-b474-520fe563bff8)

----

```[tasklist]
### Tasks
- [x] Make side-nav scrollable without displaying scrollbars on Windows
- [x] Bug: Search dropdown doesn't close when clicking on the top portion of the screen
- [x] Bug: Clicking on right-nav anchors do not scroll to the correct position on page
- [x] Bug: Arrow icons show a flashing border on page load
- [x] Make sub-level sections have optional "Overview" pages
```
