### ISSUE TITLE
Docs issue list for 11.7 feature launch

### ISSUE THREAD

**Issue by cwilhit** [upbound/docs#530]
```[tasklist]
### Tasks
- [ ] How to use ImageConfig API with Official Provider versions, put on docs.upbound.io
- [ ] How to use ImageConfig API generically, put on docs.crossplane.io
- [ ] How to do signature verification with the new signed Official providers
- [ ] Environment Configs docs on Upbound
- [ ] General docs on Official Provider support and availability logistics
- [ ] Describe how to do repo management in marketplace (since users can self-service private/public)
```
