### ISSUE TITLE
DevEx Docs Needed for 11/7

### ISSUE THREAD

**Issue by hl782** [upbound/docs#531]
Documentation Structure
- Get started with Unbound
    - Overview
    - E2E Tutorial/Walkthrough w multi language support
- Tutorials
    - Best practices with KCL
    - Best practices with Python
- Concepts
    - Control Plane Projects
    - Creating Control Plane Projects
    - How to add dependencies to a Control Plane Project
    - How to compose resources with Control Plane Projects
    - Testing Control Plane Projects
    - Building & Pushing Control Plane Projects

There is a bunch of content already prewritten. Would greatly appreciate some help.

```[tasklist]
### Tasks
- [ ] Get started with Unbound > Overview
- [ ] Get started with Unbound > E2E Tutorial/Walkthrough w multi language support
- [ ] Tutorials > Best practices with KCL
- [ ] Tutorials > Best practices with Python
- [ ] Concepts > Control Plane Projects (https://github.com/upbound/docs/pull/533)
- [ ] Concepts > Creating Control Plane Projects
- [ ] Concepts > How to add dependencies to a Control Plane Project
- [ ] Concepts > How to compose resources with Control Plane Projects
- [ ] Concepts > Testing Control Plane Projects
- [ ] Concepts > Building & Pushing Control Plane Projects
- [ ] Concepts > KCL Concepts (https://github.com/upbound/docs/pull/534)
- [ ] Concepts > Python Concepts 
```
